// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tybrvswyrnpxdrgchkwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YnJ2c3d5cm5weGRyZ2Noa3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MzA4NTMsImV4cCI6MjA4OTQwNjg1M30.uR-xcfADViPASwIz5reHa8UUv4cw1EDSp9Ofx1zlcxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});